//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministradorEntidades.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public int FacturaId { get; set; }
        public string ProveedorFactura { get; set; }
        public string ConsecutivoFactura { get; set; }
        public decimal MontoFactura { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string EstadoFactura { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
