//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministradorEntidades.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasCambio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotasCambio()
        {
            this.ProductosNC = new HashSet<ProductosNC>();
        }
    
        public int IdNC { get; set; }
        public string ConsecutivoNC { get; set; }
        public System.DateTime FechaEmisionNC { get; set; }
        public string CodProveedorNC { get; set; }
        public decimal MontoNC { get; set; }
        public int IdFacturaAplicada { get; set; }
        public string EstadoNC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductosNC> ProductosNC { get; set; }
    }
}
